### ISSUE TITLE
API

### ISSUE THREAD

**Issue by rayshan** [bower/stats#2]
# WIP NOT FINAL

Serve per-package stats like:
https://atom.io/packages
https://www.npmjs.org/package/bower
https://sublime.wbond.net/packages/Bower

## Versioning

Commit to only addition, no modification between major version bumps

### Moving work to http://docs.bower.apiary.io/

`GET /api/1/data/all`
Currently live, serving stats.bower.io web client
Mixture of different data
Endpoint probably need to be renamed

`GET /api/1/pkg/all`
Data dump of stats on all packages
Pagination?

`GET /api/1/pkg/:package`

```json
{
  "apiVer": 1,
  "dataFreshness": 1402559473,
  "package": {
    "name": "jquery",
    "rank": {
      "current": 1,
      "prior": 1,
      "velocity": 8291
    },
    "users": {
      "current": 8934,
      "prior": 8853
    },
    "installs": {
      "current": 18399,
      "prior": 18649
    }
  }
}
```

Tags / categories in here too or fetch separately from bower registry?
Trailing 7 days / 30 days / more?
Total for the period or per day? `[100, 200, 300, 400, 500, 600, 700]`

## Rate Limit

TBD

## Load Testing Results

http://stats.bower.io/api/1/data/all tested to 50 concurrent connections with constant response time:
http://loadimpact.com/load-test/stats.bower.io-c7e579dde69a4b58de18f74e831600e4

**Comment by tofumatt** [comment]
Any news on this re: package information? I'd love to be able to get bower data for the packages I maintain.

**Comment by analog-nico** [comment]
+1

**Comment by JemarJones** [comment]
+1

**Comment by samuelli** [comment]
@rayshan is this something that's going to happen?

**Comment by sheerun** [comment]
I don't think so. @satazor is working on something similar, but for npm: https://npms.io/
